recaptcha {

    // Include the noscript tags in the generated captcha
    includeNoScript = true

    // Force language change. See this for more: http://code.google.com/p/recaptcha/issues/detail?id=133
    forceLanguageInURL = false
}

mailhide {
    // Generated by the Mailhide service
    publicKey = ""
    privateKey = ""
}

environments {
    development {
        recaptcha {
            // Set to false to disable the display of captcha
            enabled = false

            // Communicate using HTTPS
            useSecureAPI = false

            // These keys are generated by the ReCaptcha service (applies to localhost)
            publicKey = "6LfuwtoSAAAAAHDphF25mbDk4DuQKIcJUV7dRDQH"
            privateKey = "6LfuwtoSAAAAAIEie_9MUfwNAdeEQxO2jVq9cMXu"

        }
    }
    production {
        recaptcha {
            // Set to false to disable the display of captcha
            enabled = true

            // Communicate using HTTPS
            useSecureAPI = true

            publicKey = System.getenv("RECAPTCHA_PUBLIC")        //TODO: change this
            privateKey = System.getenv("RECAPTCHA_PRIVATE")      //TODO: change this

        }
    }
}